name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: Print a greeting
      - run: echo Hi from our first workflow!
      - name: Start MySQL
      - run: |
          brew install mysql-client
      - uses: actions/checkout@v2
      - run: |
          make
