name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-10.15
    #services:
    #  mysql:
    #    image: mysql:5.7
    #    env:
    #      MYSQL_ROOT_PASSWORD: password
    #    ports:
    #    - 3306
    #steps:
    #  - name: Verify MySQL connection from host
    #    run:
    #      sudo apt-get install -y mysql-client 
    #     mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW DATABASES"
    steps:
      - name: Print a greeting                             
        run: echo Hi from our first workflow!
    #- uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    #- name: make
    #  run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
